import os

from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from typing import TypedDict
from langgraph.graph import StateGraph, END
from pydantic import BaseModel
from release_rules import assess_release
from langgraph.checkpoint.memory import InMemorySaver

from github_client import (
    get_open_issues,
    simplify_issues,
    count_issues_by_severity,
    get_latest_workflow_run,
    simplify_workflow_run,
)


# Load environment variables from the local .env file.
# This is where sensitive/configurable values such as OPENAI_API_KEY are stored.
load_dotenv()


# -------------------------------------------------------------------
# OPENAI MODEL HELPERS
# -------------------------------------------------------------------

def get_structured_model():
    """
    Create the OpenAI model used to generate the release explanation.

    The model is created lazily inside this function instead of at module
    import time. This is important for testing and CI because tests can
    import this module without requiring a real OPENAI_API_KEY immediately.

    The model is wrapped with Pydantic structured output so we receive a
    predictable ReleaseExplanation object instead of arbitrary free text.
    """

    openai_key = os.getenv("OPENAI_API_KEY")

    if not openai_key:
        raise ValueError(
            "OPENAI_API_KEY is required to generate the explanation."
        )

    model = ChatOpenAI(
        api_key=openai_key,
        model="gpt-5-mini",
    )

    return model.with_structured_output(ReleaseExplanation)


# -------------------------------------------------------------------
# LANGGRAPH STATE
# -------------------------------------------------------------------

class ReleaseState(TypedDict):
    """
    Shared state that moves through the LangGraph workflow.

    Each node receives the current state, performs one responsibility,
    and returns only the fields it wants to update.

    LangGraph then merges those updates into the overall workflow state.
    """

    # Engineering evidence collected from GitHub.
    release_evidence: dict

    # Deterministic release decision:
    # GO / GO WITH CONDITIONS / NO-GO.
    decision: str

    # Structured explanation generated by the LLM.
    explanation: dict

    # Operational action associated with the release decision.
    # Example: release / conditional_release / block_release.
    action_type: str

    # Structured feedback from the AI reviewer.
    review: dict

    # Number of times the explanation has been revised.
    # This prevents an unlimited AI revision loop.
    revision_count: int

    # Final review state, for example:
    # approved / max_revisions_reached / human_approved.
    review_status: str

    # True when automated review could not resolve the explanation
    # and the workflow must escalate to a human.
    human_review_required: bool

    # Human choice received later through the API/UI.
    # Example: Approve / Reject / Request Changes.
    human_decision: str


# -------------------------------------------------------------------
# GITHUB EVIDENCE NODE
# -------------------------------------------------------------------

def fetch_release_evidence(state: ReleaseState):
    """
    Fetch the factual engineering signals used for release assessment.

    GitHub is the source of truth for:
    - open issues
    - issue severity
    - latest GitHub Actions / CI result

    This node does not make any release decision. Its only responsibility
    is to gather and normalize the evidence required by later nodes.
    """

    # Fetch currently open GitHub issues.
    issues = get_open_issues()

    # Reduce the large GitHub API response to only the fields
    # ReleaseGuard actually needs.
    simplified_issues = simplify_issues(issues)

    # Convert the issue list into severity totals.
    severity_counts = count_issues_by_severity(simplified_issues)

    # Fetch the latest GitHub Actions workflow run.
    workflow_data = get_latest_workflow_run()

    # Convert the raw workflow response into a smaller structure
    # containing CI status, conclusion, and branch.
    workflow_result = simplify_workflow_run(workflow_data)

    # Combine all factual engineering signals into one evidence object.
    release_evidence = {
        "ci_passed": workflow_result["ci_passed"],
        "ci_status": workflow_result["status"],
        "ci_conclusion": workflow_result["conclusion"],
        "branch": workflow_result["branch"],
        "critical_issues": severity_counts["critical"],
        "high_issues": severity_counts["high"],
        "medium_issues": severity_counts["medium"],
        "low_issues": severity_counts["low"],
    }

    # LangGraph nodes return only the state fields they want to update.
    return {
        "release_evidence": release_evidence
    }


# -------------------------------------------------------------------
# DETERMINISTIC RELEASE DECISION NODE
# -------------------------------------------------------------------

def evaluate_release(state: ReleaseState):
    """
    Apply deterministic release rules to the GitHub evidence.

    The LLM does NOT decide whether the release is GO or NO-GO.

    Release gating is intentionally handled by normal Python rules because
    these decisions should be predictable, testable, and auditable.
    """

    evidence = state["release_evidence"]

    # assess_release() lives in release_rules.py.
    # Keeping the business rules separate makes them easy to unit test.
    decision = assess_release(
        ci_passed=evidence["ci_passed"],
        critical_issues=evidence["critical_issues"],
        high_issues=evidence["high_issues"],
    )

    return {
        "decision": decision
    }


# -------------------------------------------------------------------
# STRUCTURED LLM OUTPUT MODELS
# -------------------------------------------------------------------

class ReleaseExplanation(BaseModel):
    """
    Required structure for the AI-generated explanation.

    Structured output makes the response predictable for FastAPI,
    Streamlit, tests, and later workflow nodes.
    """

    summary: str
    risk_level: str
    recommended_action: str


class ReleaseReview(BaseModel):
    """
    Required structure for the AI reviewer.

    needs_revision is especially important because LangGraph uses it
    to decide whether the explanation should go through another revision.
    """

    is_consistent: bool
    review_comment: str
    needs_revision: bool


# -------------------------------------------------------------------
# AI EXPLANATION NODE
# -------------------------------------------------------------------

def generate_explanation(state: ReleaseState):
    """
    Generate a human-readable explanation of the deterministic decision.

    Important design choice:
    the LLM explains the decision but is explicitly told not to change it.

    This separates:
        deterministic governance -> Python
        contextual explanation   -> LLM
    """

    evidence = state["release_evidence"]
    decision = state["decision"]
    action_type = state["action_type"]

    prompt = f"""
You are assisting a software release manager.

Release evidence:
- CI passed: {evidence["ci_passed"]}
- Critical issues: {evidence["critical_issues"]}
- High issues: {evidence["high_issues"]}
- Medium issues: {evidence["medium_issues"]}
- Low issues: {evidence["low_issues"]}

Deterministic release decision:
{decision}
Action type: {action_type}

Do not change the decision or action type.

Provide:
- a short summary
- a risk level
- a recommended action
Keep the recommended action concise.
"""

    # Create the structured model only when this node actually runs.
    structured_model = get_structured_model()

    # Invoke the LLM.
    # Because structured output is enabled, response is a
    # ReleaseExplanation Pydantic object.
    response = structured_model.invoke(prompt)

    # Convert the Pydantic object into a normal dictionary
    # before storing it in LangGraph state.
    return {
        "explanation": response.model_dump()
    }


# -------------------------------------------------------------------
# AI REVIEWER MODEL
# -------------------------------------------------------------------

def get_review_model():
    """
    Create the separate model used to review the generated explanation.

    This is also created lazily so importing release_graph.py does not
    require an OpenAI key during tests or CI.
    """

    openai_key = os.getenv("OPENAI_API_KEY")

    if not openai_key:
        raise ValueError(
            "OPENAI_API_KEY is required to review the explanation."
        )

    model = ChatOpenAI(
        api_key=openai_key,
        model="gpt-5-mini",
    )

    return model.with_structured_output(ReleaseReview)


# -------------------------------------------------------------------
# AI REVIEW NODE
# -------------------------------------------------------------------

def review_explanation(state: ReleaseState):
    """
    Review whether the generated explanation agrees with the
    deterministic release decision and selected action.

    The purpose is not to reconsider the release decision itself.
    The reviewer checks the quality and consistency of the AI explanation.
    """

    explanation = state["explanation"]
    decision = state["decision"]
    action_type = state["action_type"]

    review_model = get_review_model()

    prompt = f"""
You are reviewing an AI-generated software release recommendation.

Deterministic decision:
{decision}

Action type:
{action_type}

AI explanation:
{explanation}

Check whether the explanation is consistent with the deterministic decision
and action type.

Respond with one short sentence saying whether it is consistent.
"""

    response = review_model.invoke(prompt)

    return {
        "review": response.model_dump()
    }


# -------------------------------------------------------------------
# AI REVISION NODE
# -------------------------------------------------------------------

def revise_explanation(state: ReleaseState):
    """
    Revise the explanation when the AI reviewer identifies a problem.

    The reviewer feedback is given back to the explanation model so it can
    correct the explanation while preserving the original deterministic
    release decision.

    revision_count is increased each time this node runs.
    """

    evidence = state["release_evidence"]
    decision = state["decision"]
    action_type = state["action_type"]
    explanation = state["explanation"]
    review = state["review"]

    structured_model = get_structured_model()

    revision_count = state["revision_count"]

    prompt = f"""
You are revising a software release explanation.

Release evidence:
{evidence}

Deterministic decision:
{decision}

Action type:
{action_type}

Current explanation:
{explanation}

Reviewer feedback:
{review}

Revise the explanation so that it is fully consistent with the deterministic
decision and action type.

Do not change the decision or action type.

Keep the response concise.
"""

    response = structured_model.invoke(prompt)

    return {
        "explanation": response.model_dump(),
        "revision_count": revision_count + 1,
    }


# -------------------------------------------------------------------
# REVIEW ROUTING
# -------------------------------------------------------------------

def route_review(state: ReleaseState):
    """
    Decide whether the explanation should be revised again.

    A maximum of two revisions is allowed. This prevents an uncontrolled
    agent loop where the AI could repeatedly review and revise forever.
    """

    review = state["review"]
    revision_count = state["revision_count"]

    # Revision is allowed only if:
    # 1. the reviewer says a revision is needed, and
    # 2. fewer than two revisions have already happened.
    if review["needs_revision"] and revision_count < 2:
        return "revise"

    # Otherwise move toward final review status.
    return "end"


# -------------------------------------------------------------------
# FINAL REVIEW STATUS NODE
# -------------------------------------------------------------------

def finalize_review_status(state: ReleaseState):
    """
    Convert the AI review result into a final workflow status.

    If the explanation is accepted, the workflow is approved.

    If two revisions have already happened and the reviewer still requests
    another revision, automated attempts stop and the workflow escalates
    to a human reviewer.
    """

    review = state["review"]
    revision_count = state["revision_count"]

    if not review["needs_revision"]:
        status = "approved"
        human_review_required = False

    elif revision_count >= 2:
        # Safety boundary: automated revision has reached its limit.
        status = "max_revisions_reached"
        human_review_required = True

    else:
        # This branch is mainly defensive. Under the current routing logic,
        # the graph normally revises again before reaching this state.
        status = "pending"
        human_review_required = False

    return {
        "review_status": status,
        "human_review_required": human_review_required,
    }


# -------------------------------------------------------------------
# RELEASE DECISION HANDLERS
# -------------------------------------------------------------------

def handle_go(state: ReleaseState):
    """
    Convert a GO decision into the operational release action.
    """

    return {
        "action_type": "release"
    }


def handle_go_with_conditions(state: ReleaseState):
    """
    Convert GO WITH CONDITIONS into a conditional release action.
    """

    return {
        "action_type": "conditional_release"
    }


def handle_no_go(state: ReleaseState):
    """
    Convert NO-GO into an explicit release-blocking action.
    """

    return {
        "action_type": "block_release"
    }


# -------------------------------------------------------------------
# RELEASE ROUTER
# -------------------------------------------------------------------

def route_release(state: ReleaseState):
    """
    Route the graph to the correct branch based on the deterministic
    release decision.
    """

    decision = state["decision"]

    if decision == "GO":
        return "go"

    elif decision == "GO WITH CONDITIONS":
        return "go_with_conditions"

    else:
        return "no_go"


# -------------------------------------------------------------------
# HUMAN-IN-THE-LOOP DECISION LOGIC
# -------------------------------------------------------------------

def apply_human_decision(state: ReleaseState):
    """
    Translate a human review choice into LangGraph state updates.

    Human input is received later through FastAPI/Streamlit and written
    into the checkpointed state.

    Keeping these rules here avoids duplicating the decision mapping
    inside the API layer.
    """

    human_decision = state["human_decision"]

    if human_decision == "Approve":
        return {
            "review_status": "human_approved",
            "human_review_required": False,
        }

    elif human_decision == "Reject":
        return {
            "review_status": "human_rejected",
            "human_review_required": False,

            # A human rejection explicitly blocks the release.
            "action_type": "block_release",
        }

    elif human_decision == "Request Changes":
        return {
            "review_status": "changes_requested",

            # The workflow remains open for further human attention.
            "human_review_required": True,
        }

    # Defensive fallback if the function receives an unexpected value.
    # The FastAPI request model currently prevents unsupported choices.
    return {}


# ===================================================================
# BUILD THE LANGGRAPH WORKFLOW
# ===================================================================

# Create a stateful graph using ReleaseState as the shared state schema.
builder = StateGraph(ReleaseState)


# -------------------------------------------------------------------
# REGISTER GRAPH NODES
# -------------------------------------------------------------------

# Step 1: collect live GitHub evidence.
builder.add_node(
    "fetch_release_evidence",
    fetch_release_evidence,
)

# Step 2: apply deterministic release rules.
builder.add_node(
    "evaluate_release",
    evaluate_release,
)

# Generate the AI explanation after the release path has been selected.
builder.add_node(
    "generate_explanation",
    generate_explanation,
)

# Decision-specific handler nodes.
builder.add_node(
    "handle_go",
    handle_go,
)

builder.add_node(
    "handle_go_with_conditions",
    handle_go_with_conditions,
)

builder.add_node(
    "handle_no_go",
    handle_no_go,
)

# AI quality-control nodes.
builder.add_node(
    "review_explanation",
    review_explanation,
)

builder.add_node(
    "revise_explanation",
    revise_explanation,
)

# Convert the final AI review result into workflow status.
builder.add_node(
    "finalize_review_status",
    finalize_review_status,
)

# Human decision logic.
# The current API calls this function directly when applying human input,
# but it is also registered as a graph node for workflow extensibility.
builder.add_node(
    "apply_human_decision",
    apply_human_decision,
)


# -------------------------------------------------------------------
# DEFINE THE MAIN GRAPH FLOW
# -------------------------------------------------------------------

# The workflow always begins by collecting factual GitHub evidence.
builder.set_entry_point("fetch_release_evidence")


# After evidence collection, evaluate the deterministic release decision.
builder.add_edge(
    "fetch_release_evidence",
    "evaluate_release",
)


# Route to one of three branches depending on the release decision.
#
# evaluate_release
#       ↓
#   route_release
#    ↙    ↓     ↘
#   GO   CONDITIONAL   NO-GO
builder.add_conditional_edges(
    "evaluate_release",
    route_release,
    {
        "go": "handle_go",
        "go_with_conditions": "handle_go_with_conditions",
        "no_go": "handle_no_go",
    },
)


# -------------------------------------------------------------------
# DEFINE AI REVIEW / REVISION ROUTING
# -------------------------------------------------------------------

# After the explanation is reviewed:
#
# needs revision + revision_count < 2
#        → revise_explanation
#
# otherwise
#        → finalize_review_status
builder.add_conditional_edges(
    "review_explanation",
    route_review,
    {
        "revise": "revise_explanation",
        "end": "finalize_review_status",
    },
)


# -------------------------------------------------------------------
# CONVERGE RELEASE BRANCHES
# -------------------------------------------------------------------

# All three decision branches converge into the same explanation step.
builder.add_edge(
    "handle_go",
    "generate_explanation",
)

builder.add_edge(
    "handle_go_with_conditions",
    "generate_explanation",
)

builder.add_edge(
    "handle_no_go",
    "generate_explanation",
)


# -------------------------------------------------------------------
# AI EXPLANATION + REVIEW LOOP
# -------------------------------------------------------------------

# First explanation → AI review.
builder.add_edge(
    "generate_explanation",
    "review_explanation",
)

# Revised explanation → AI review again.
# This edge creates the bounded review/revision loop.
builder.add_edge(
    "revise_explanation",
    "review_explanation",
)


# -------------------------------------------------------------------
# HUMAN DECISION PATH
# -------------------------------------------------------------------

# If apply_human_decision is run as a graph node, there is no further
# automated workflow after the human choice, so the node terminates at END.
builder.add_edge(
    "apply_human_decision",
    END,
)


# The normal automated assessment finishes after the final review status
# has been calculated.
builder.set_finish_point(
    "finalize_review_status"
)


# -------------------------------------------------------------------
# CHECKPOINTING
# -------------------------------------------------------------------

# InMemorySaver stores LangGraph checkpoints for each thread_id.
#
# This allows:
# - retrieving the latest assessment state
# - keeping different assessments isolated
# - adding a human decision later through graph.update_state()
#
# Limitation:
# this storage exists only in the current Python process.
# Restarting the application removes the saved checkpoints.
checkpointer = InMemorySaver()


# Compile the graph into the executable object used by:
# - app.py
# - FastAPI
# - Streamlit via the API
# - automated tests
graph = builder.compile(
    checkpointer=checkpointer
)